In [1]:
import numpy as np

#### 1) 2-dən 10-a qədər dəyərlərlə 3x3 matris yaradan proqram yazın. Nəticəni çap edin.

In [2]:
matris = np.arange(2, 11).reshape(3, 3)

In [3]:
matris

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### 2) NumPy massivində saxlanılan Selsiy dərəcələrini Fahrenheit dərəcələrinə çevirən proqram yazın.
#### Nümunə massivi:
####        Fahrenheit dərəcələrindəki qiymətlər [0, 12, 45.21, 34, 99.91]
####        Selsiy dərəcələrindəki qiymətlər [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

In [4]:
c = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.0])
f = np.round((c * 9 / 5) + 32, 2)

In [5]:
f

array([-0.  , 12.  , 45.21, 34.  , 99.91, 32.  ])

#### 3) Bir massiv yaradın, həmin massivdə maximum və minimum dəyərlərin indekslərini tapan proqram yazın. Nəticələri çap edin.

In [13]:
arr = np.array([5, -3, 2, 18, 9, 3, 41])

max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

In [15]:
print(f'Maximum dəyərin indeksi: {max_idx}')
print(f'Minimum dəyərin indeksi: {min_idx}')

Maximum dəyərin indeksi: 6
Minimum dəyərin indeksi: 1


#### 4) İki massiv yaradın və onların matris hasilini hesablayan proqram yazın. Nəticəni çap edin.

In [16]:
arr1 = np.array([5, -3, 2, 18, 9, 3, 41])
arr2 = np.array([15, 3, 7, 1, 12, 6, -2])


In [17]:
arr1 * arr2

array([ 75,  -9,  14,  18, 108,  18, -82])

#### 5) 2D ölçülü massiv yaradın (2 sətir və 3 sütunlu ölçüdə olsun). Həmin matrisin bütün elementlərinin, hər 3 sütun üçün sətirləri üzrə elementlərinin, və hər 2 sətir üçün sütunları üzrə elementlərinin kumulyativ cəmlərini hesablayan proqram yazın. Nəticələri çap edin.

#### 6) Bir matris yaradın. Həmin matrisin natural, 10 əsaslı və 2 əsaslı logarifmləri hesablayan proqram yazın. Nəticələri çap edin.

In [25]:
matris = np.array([1, 10, 100])

log_e = np.log(matris)
log_10 = np.log10(matris)
log_2 = np.log2(matris)

In [ ]:
print(f'{log_e}\n {log_10}\n {log_2}')

[0.         2.30258509 4.60517019]
 [0. 1. 2.]
 [0.         3.32192809 6.64385619]


#### 7) Bir matris yaradın və onun determinantını hesablayan proqram yazın. Nəticəni çap edin.

In [42]:
matrix = np.array([
    [3, 2],
    [3, 4]])

det = np.linalg.det(matrix).round(2)

In [43]:
det

np.float64(6.0)

#### 8) 5x5 ölçülü vahid matris yaradın və sonra diaqonalı 1-dən 5-ə qədər dəyərlərlə əvəz edin. Nəticəni çap edin.

In [47]:
matrix = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

In [48]:
matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 9) İki matris yaradın və onların kovariasiya matrisini hesablayan proram yazın. Nəticəni çap edin.

In [49]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]])

B = np.array([
    [2, 4, 6],
    [1, 3, 5]])

cov_mtrx = np.cov(A, B)

In [50]:
cov_mtrx

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [2., 2., 4., 4.],
       [2., 2., 4., 4.]])

#### 10) 0 və 1 arasında yerləşən təsadüfi 10 dəyərdən ibarət 1D matris (vektor) yaradın, sonra onu sıralayan proqram yazın. Nəticəni çap edin.

In [53]:
vector = np.random.rand(10).round(2)
sorted_vector = np.sort(vector)

In [54]:
sorted_vector

array([0.09, 0.29, 0.3 , 0.35, 0.37, 0.7 , 0.79, 0.84, 0.87, 0.92])