In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [2]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr3 = np.array([[[1,2,3],
                    [4,5,6]],
                 [[10,20,30],
                    [40,50,60]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [4]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)
print(type(arr1))

(5,)
1
int64
5
<class 'numpy.ndarray'>


In [5]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(type(arr2))

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


In [6]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)
print(arr3.size)
print(type(arr3))

(2, 2, 3)
3
int64
12
<class 'numpy.ndarray'>


In [7]:
import pandas as pd
df = pd.DataFrame(arr2)

df

,0,1,2
0,1,2,3
1,4,5,6


In [8]:
arr_ones = np.ones((10,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
arr_zeros = np.zeros((7, 2, 3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
arr_range = np.arange(0 , 100 , 3)
arr_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
arr = np.random.randint(0, 10, size=(7, 2))
arr

array([[4, 7],
       [0, 5],
       [5, 4],
       [5, 8],
       [8, 1],
       [6, 6],
       [9, 6]])

In [12]:
arr_flaot = np.random.rand(3,5)
arr_flaot

array([[0.70941411, 0.82465337, 0.58842941, 0.13651388, 0.36903399],
       [0.08084842, 0.18597494, 0.07246256, 0.58782097, 0.36119164],
       [0.24101368, 0.68664971, 0.02743882, 0.6129912 , 0.45273177]])

In [13]:
arr = np.random.randint( 0 , 10 , size=(4, 6))
np.random.seed(42)
arr


array([[8, 4, 4, 4, 5, 0],
       [7, 9, 6, 5, 1, 0],
       [6, 3, 8, 5, 9, 8],
       [8, 5, 9, 8, 5, 2]])

In [14]:
random_arr = np.random.randint(1, 11, size=(3, 7))
random_arr

array([[ 7,  4,  8,  5,  7, 10,  3],
       [ 7,  8,  5,  4,  8,  8,  3],
       [ 6,  5,  2,  8,  6,  2,  5]])

In [15]:
unique_arr = np.unique(random_arr)
unique_arr

array([ 2,  3,  4,  5,  6,  7,  8, 10])

In [16]:
random_arr[0]


array([ 7,  4,  8,  5,  7, 10,  3])

In [17]:
random_arr[0:2]


array([[ 7,  4,  8,  5,  7, 10,  3],
       [ 7,  8,  5,  4,  8,  8,  3]])

In [18]:
random_arr[0:2 , 0:2]

array([[7, 4],
       [7, 8]])

In [19]:
arr5 = np.random.randint(0,10 , size=(3,5))
arr5_ones = np.ones((3,5))
print(arr5)
print("----------")
print(arr5_ones)

[[0 9 5 8 0]
 [9 2 6 3 8]
 [2 4 2 6 4]]
----------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
arr5_sum = arr5 + arr5_ones
arr5_sum


array([[ 1., 10.,  6.,  9.,  1.],
       [10.,  3.,  7.,  4.,  9.],
       [ 3.,  5.,  3.,  7.,  5.]])

In [21]:
arr6 = np.ones((5,3))
arr6


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr7 = np.ones((3,5))
arr7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
arr8 = arr5_sum - arr7
arr8


array([[0., 9., 5., 8., 0.],
       [9., 2., 6., 3., 8.],
       [2., 4., 2., 6., 4.]])

In [25]:
arr9 = arr8 * arr7
arr9

array([[0., 9., 5., 8., 0.],
       [9., 2., 6., 3., 8.],
       [2., 4., 2., 6., 4.]])

In [26]:
arr10_1 = arr9 ** 2
arr10_1

array([[ 0., 81., 25., 64.,  0.],
       [81.,  4., 36.,  9., 64.],
       [ 4., 16.,  4., 36., 16.]])

In [27]:
arr10_2 = np.square(arr9)
arr10_2

array([[ 0., 81., 25., 64.,  0.],
       [81.,  4., 36.,  9., 64.],
       [ 4., 16.,  4., 36., 16.]])

In [28]:
np.mean(arr10_2)


np.float64(29.333333333333332)

In [29]:
np.max(arr10_2)

np.float64(81.0)

In [30]:
np.min(arr10_2)

np.float64(0.0)

In [31]:
np.std(arr10_2)

np.float64(28.595259902453922)

In [32]:
np.var(arr10_2)

np.float64(817.688888888889)

In [33]:
arr10_2.reshape (3, 5, 1)


array([[[ 0.],
        [81.],
        [25.],
        [64.],
        [ 0.]],

       [[81.],
        [ 4.],
        [36.],
        [ 9.],
        [64.]],

       [[ 4.],
        [16.],
        [ 4.],
        [36.],
        [16.]]])

In [34]:
arr10_2.T

array([[ 0., 81.,  4.],
       [81.,  4., 16.],
       [25., 36.,  4.],
       [64.,  9., 36.],
       [ 0., 64., 16.]])

In [35]:
r1 = np.random.randint(0, 10, size=(3, 3))
r2 = np.random.randint(0, 10, size=(3, 2))

print(r1)
print("----------")
print(r2)

[[8 6 1]
 [3 8 1]
 [9 8 9]]
----------
[[4 1]
 [3 6]
 [7 2]]


In [36]:
np.dot(r1, r2)

array([[ 57,  46],
       [ 43,  53],
       [123,  75]])

In [37]:
r3 = np.random.randint(0, 10, size=(4, 3))
r4 = np.random.randint(0, 10, size=(4, 3))
print(r3)
print("----------")
print(r4)

[[0 3 1]
 [7 3 1]
 [5 5 9]
 [3 5 1]]
----------
[[9 1 9]
 [3 7 6]
 [8 7 4]
 [1 4 7]]


In [39]:
np.dot(r3, r4.T)

array([[ 12,  27,  25,  19],
       [ 75,  48,  81,  26],
       [131, 104, 111,  88],
       [ 41,  50,  63,  30]])

In [40]:
r5 = np.random.randint(0, 10, size=(3, 3))
r6 = np.random.randint(0, 10, size=(3, 3))
print(r5)
print("----------")
print(r6)

[[9 8 8]
 [0 8 6]
 [8 7 0]]
----------
[[7 7 2]
 [0 7 2]
 [2 0 4]]


In [41]:
r5 > r6

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [42]:
r5 >= r6


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [43]:
r5 > 7

array([[ True,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [44]:
r5 == r6

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [45]:
np.sort(r5)

array([[8, 8, 9],
       [0, 6, 8],
       [0, 7, 8]])

In [46]:
np.argsort(r5)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0]])

In [47]:
np.argmax(r5)

np.int64(0)

In [48]:
np.argmin(r5)

np.int64(3)

In [49]:
np.argmax(r5, axis=1)

array([0, 1, 0])

In [50]:
np.argmin(r5, axis=0)

array([1, 2, 2])

In [51]:
np.random.randn(10)

array([ 0.21158701,  0.59704465, -0.89633518, -0.11198782,  1.46894129,
       -1.12389833,  0.9500054 ,  1.72651647,  0.45788508, -1.68428738])

In [52]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])